blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.PostListView.as_view(), name="list"),
    path("criar/", views.PostCreateView.as_view(), name="create"),
    path("category/<slug:slug>/", views.PostListView.as_view(), name="list_by_category"),
    path("post/<slug:slug>/", views.PostDetailView.as_view(), name="detail"),
    path("favorito/", views.FavoriteView.as_view(), name="favorite"),    
]

payments/urls.py
from django.urls import path

from .views import (
    PaymentCreateView,
    PaymentFailureView,
    PaymentPendingView,
    PaymentSuccessView,
    payment_webhook,
)

app_name = "payments"

urlpatterns = [
    path("process/", PaymentCreateView.as_view(), name="process"),
    path("failure/", PaymentFailureView.as_view(), name="failure"),
    path("pending/", PaymentPendingView.as_view(), name="pending"),
    path("success/", PaymentSuccessView.as_view(), name="success"),
    path("webhook/", payment_webhook, name="webhook"),
]

pycom/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("produtos/", include("products.urls")),
    path("carrinho/", include("cart.urls")),
    path("", include("pages.urls")),
    path("orders/",include("orders.urls")),    
    path("accounts/",include("allauth.urls")),
    path("payments/", include("payments.urls")),
    path("blog/", include("blog.urls")),
    path("perfil/", include("users.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

payments/models.py
from django.db import models
from localflavor.br.models import BRCPFField
from model_utils.models import TimeStampedModel

from orders.models import Order


class Payment(TimeStampedModel):
    order = models.ForeignKey(Order, related_name="payments", on_delete=models.CASCADE)
    transaction_amount = models.DecimalField(
        "Valor da Transação", max_digits=10, decimal_places=2
    )
    installments = models.IntegerField("Parcelas")
    payment_method_id = models.CharField("Método de Pagamento", max_length=250)
    email = models.EmailField()
    doc_number = BRCPFField("CPF")
    mercado_pago_id = models.CharField(max_length=250, blank=True, db_index=True)
    mercado_pago_status = models.CharField(max_length=250, blank=True)
    mercado_pago_status_detail = models.CharField(max_length=250, blank=True)

    class Meta:
        ordering = ("-modified",)

    def __str__(self):
        return f"Pagamento {self.id}"

payments/forms.py
import mercadopago
from django import forms
from django.conf import settings

from .models import Payment


class paymentForm(forms.ModelForm):
    token = forms.CharField()
    print("nem rodei ainda")
    class Meta:
        model = Payment
        fields = [
            "transaction_amount",
            "installments",
            "payment_method_id",
            "email",
            "doc_number",
        ]

    def __init__(self, *args, **kwargs):
        self.order = kwargs.pop("order")
        super().__init__(*args, **kwargs)

    def clean_transaction_amount(self):
        transaction_amount = self.cleaned_data["transaction_amount"]
        if float(transaction_amount) != float(self.order.get_total_price()):
            raise forms.ValidationError(
                "Transaction Amount não bate com o banco de dados!"
            )
        return transaction_amount

    def save(self):
        cd = self.cleaned_data
        mp = mercadopago.SDK(settings.MERCADO_PAGO_ACCESS_TOKEN)
        payment_data = {
            "transaction_amount": float(self.order.get_total_price()),
            "token": cd["token"],
            "description": self.order.get_description(),
            "installments": cd["installments"],
            "payment_method_id": cd["payment_method_id"],
            "payer": {
                "email": cd["email"],
                "identification": {"type": "CPF", "number": cd["doc_number"]},
            },
        }
        payment = mp.payment().create(payment_data)
        print("cheguei aqui")

        if payment["status"] == 201:
            self.instance.order = self.order
            self.instance.mercado_pago_id = payment["response"]["id"]
            self.instance.mercado_pago_status_detail = payment["response"][
                "status_detail"
            ]
            self.instance.mercado_pago_status = payment["response"]["status"]

            if payment["response"]["status"] == "approved":
                self.order.paid = True
                self.order.save()
            self.instance.save()


class UpdatepaymentForm(forms.Form):
    action = forms.CharField()
    data = forms.JSONField()

    def save(self):
        cd = self.cleaned_data
        mp = mercadopago.SDK(settings.MERCADO_PAGO_ACCESS_TOKEN)
        if cd["action"] == "payment.updated":
            mercado_pago_id = cd["data"]["id"]
            payment = Payment.objects.get(mercado_pago_id=mercado_pago_id)
            payment_mp = mp.payment().get(mercado_pago_id)

            payment.mercado_pago_status = payment_mp["response"]["status"]
            payment.mercado_pago_status_detail = payment_mp["response"]["status_detail"]

            if payment_mp["response"]["status"] == "approved":
                payment.order.paid = True
            else:
                payment.order.paid = False

            payment.order.save()
            payment.save()

payments/views.py
import json

from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.utils.functional import cached_property
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.views.generic import CreateView, TemplateView

from orders.models import Order

from .forms import paymentForm, UpdatepaymentForm
from .models import Payment


class PaymentCreateView(CreateView):
    model = Payment
    form_class = paymentForm

    @cached_property
    def order(self):
        order_id = self.request.session.get("order_id")
        order = get_object_or_404(Order, id=order_id)
        return order

    def get_form_kwargs(self):
        form_kwargs = super().get_form_kwargs()
        form_kwargs["order"] = self.order
        return form_kwargs

    def form_valid(self, form):
        form.save()
        redirect_url = "payments:failure"
        status = form.instance.mercado_pago_status

        if status == "approved":
            redirect_url = "payments:success"
        if status == "in_process":
            redirect_url = "payments:pending"

        if status and status != "rejected":
            del self.request.session["order_id"]
        return redirect(redirect_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["order"] = self.order
        context["publishable_key"] = settings.MERCADO_PAGO_PUBLIC_KEY
        return context


class PaymentFailureView(TemplateView):
    template_name = "payments/failure.html"


class PaymentPendingView(TemplateView):
    template_name = "payments/pending.html"


class PaymentSuccessView(TemplateView):
    template_name = "payments/success.html"


@csrf_exempt
@require_POST
def payment_webhook(request):
    data = json.loads(request.body)
    form = UpdatepaymentForm(data)
    if form.is_valid():
        form.save()

    return JsonResponse({})

templates/payments/failure.html
{% extends "base.html" %}

{% block title %}Ooops{% endblock %}

{% block content %}

<div class="container my-3">
    <h1 class="font-weight-bold">Pagamento não realizado!</h1>
    <p>
        Alguma coisa aconteceu e o pagamento não foi feito. Tente novamente.
        Se o erro persistir entre em contato conosco.
    </p>
    <a class="btn btn-primary" href="{% url 'payments:process' %}">
        Tentar novamente
    </a>
</div>

{% endblock %}

templates/payments/payment_form.html
{% extends "base.html" %}

{% load static %}

{% block title %}Pagamento com cartão de crédito{% endblock %}

{% block content %}
{% with total_price=order.get_total_price %}

<div class="container my-3">
    <h1 class="font-weight-bold">Pagamento com cartão de crédito</h1>
    <div class="row">
        <div class="col-lg-6">
            {% if form.errors %}
            {% for field in form %}
            {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            {% endif %}
            
            
            <form action="." method="post" id="paymentForm">
                <fieldset class="border-bottom mb-3">
                    <div class="form-group">
                        <input type="text" id="paymentForm__cardholderName" placeholder="Titular do cartão" value="{{ order.name }}" class="form-control"/>
                        <input type="text" id="paymentForm__identificationNumber" name="identificationNumber"
                        value="{{ order.cpf }}" placeholder="Número do documento" class="form-control" />
                    </div>
                    <div class="form-group">
                        <input type="email" id="paymentForm__email" name="email" value="{{ order.email }}" placeholder="E-mail" class="form-control"/>
                    </div>
                    <div class="form-group">
                    </div>
                    <div class="form-group">
                        <div id="paymentForm__cardNumber" class="form-control"></div>
                    </div>
                    <select id="paymentForm__issuer" name="issuer">
                        <option value="" disabled selected>Banco emissor</option>
                    </select>
                        <div class="row">
                            <div class="form-group col-6 mb-0">
                                <label for="">Data de vencimento</label>
                                <div class="row">
                                    <div class="form-group col-6">
                                        <div id="paymentForm__expirationDate" class="form-control"></div>
                                    </div>
                                    <div class="form-group col-6">
                                        <div id="paymentForm__securityCode" class="form-control"></div>
                                    </div>          
                                </div>
                            </div>
                        </div>            
                    <div class="form-group">
                    <select id="paymentForm__installments" name="installments" class="form-control">
                    <option value="" disabled selected>Parcelas</option>
                    </select>
                    </div>
                </fieldset>
                <div>
                    <select id="paymentForm__identificationType" name="identificationType"class="form-control">
                      <option value="" disabled selected>Tipo de documento</option>
                    </select>
                    <input id="token" name="token" type="hidden" class="form-control">
                    <input id="paymentMethodId" name="paymentMethodId" type="hidden" class="form-control">
                    <input id="transactionAmount" name="transactionAmount" type="hidden" value="{{ total_price|stringformat:'.2f' }}">
                    <input id="description" name="description" type="hidden" value="Nome do Produto">
                    {% csrf_token %}
                    <br>
                    <button type="submit" id="paymentForm__submit"class="btn btn-success btn-lg btn-block">Pagar</button>
                    <br>
                </div>    
            </form>
        </div>
        <div class="col-lg-6">
            <div class="card border-0 bg-light p-4">
                {% include "order_summary.html" with items=order.items.all total_price=total_price %}
            </div>
        </div>
    </div>
</div>

{% endwith %}
{% endblock %}

{% block script %}
<script src="https://unpkg.com/imask@6.0.7/dist/imask.js"></script>
<script src="https://secure.mlstatic.com/sdk/javascript/v1/mercadopago.js"></script>
<script src="https://sdk.mercadopago.com/js/v2"></script>
<script src="{% static 'js/process-payment.js' %}"></script>

{% endblock script %}

templates/payments/pending.html
{% extends "base.html" %}

{% block title %}Sucesso!{% endblock %}

{% block content %}

<div class="container my-3">
    <h1 class="font-weight-bold">Estamos processando o seu pagamento!</h1>
    <p>
        Obrigado por comprar conosco.
        Em até 2 dias úteis você receberá um e-mail com mais informações sobre o pagamento.
    </p>
</div>

{% endblock %}

templates/payments/success.html
{% extends "base.html" %}

{% block title %}Sucesso!{% endblock %}

{% block content %}

<div class="container my-3">
    <h1 class="font-weight-bold">Pagamento efetuado com sucesso!</h1>
    <p>Obrigado por comprar conosco.</p>
</div>

{% endblock %}