blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.PostListView.as_view(), name="list"),
    path("criar/", views.PostCreateView.as_view(), name="create"),
    path("category/<slug:slug>/", views.PostListView.as_view(), name="list_by_category"),
    path("post/<slug:slug>/", views.PostDetailView.as_view(), name="detail"),
    path("favorito/", views.FavoriteView.as_view(), name="favorite"),    
]

pycom/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("produtos/", include("products.urls")),
    path("carrinho/", include("cart.urls")),
    path("", include("pages.urls")),
    path("orders/",include("orders.urls")),    
    path("accounts/",include("allauth.urls")),
    path("payments/", include("payments.urls")),
    path("blog/", include("blog.urls")),
    path("perfil/", include("users.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

blog/models.py
from users.models import User
from django.db import models
from django.urls import reverse
from autoslug import AutoSlugField
from model_utils.models import TimeStampedModel
from PIL import Image

from .utils import upload_perfil_user


class Category(TimeStampedModel):
    name = models.CharField(max_length=255, unique=True)
    slug = AutoSlugField(unique=True, always_update=False, populate_from="name")
    class Meta:
        ordering = ("name",)
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("blog:list_by_category", kwargs={"slug": self.slug})


class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = AutoSlugField(unique=True, always_update=False, populate_from="title")
    author = models.ForeignKey(User,related_name="autor", on_delete=models.CASCADE)
    body = models.TextField(max_length=1050)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    image = models.ImageField(null=True, blank=True, upload_to=upload_perfil_user)
    favorite = models.ManyToManyField(User, default=None, blank=True, related_name="favorito")   
    category = models.ForeignKey(
        Category, related_name="posts", on_delete=models.CASCADE, null=True
    )
    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"slug": self.slug})

    def comment_number(self):
        return len(self.comment_set.all())

    @property
    def favorite_number(self):
        return self.favorite.all().count()

    # redimensionando imagem para um maximo de 1300x1300 px
    def save(self):
        super().save()

        img = Image.open(self.image.path)

        if img.height > 1300 or img.width >1300 :
            output_size = (1300, 1300)
            img.thumbnail(output_size)
            img.save(self.image.path)


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)


FAVORITE_CHOICES = (
    ("Favoritar", "Favoritar"),
    ("Desfavoritar","Desfavoritar")
)
class Favorite(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="favoritado")   
    value = models.CharField(choices=FAVORITE_CHOICES, default="Favoritar", max_length=15)
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True)
    class Meta :
        constraints = (models.UniqueConstraint(fields=['author_id', 'post_id'], name='unique_favorite'),)
        def __str__(self):
            return str(self.post)

blog/forms.py
from django import forms
from .models import Post, Comment


class CreatePostForm(forms.ModelForm):

    class Meta :
        model = Post        

        fields = [            
        "title",
        "body",
        "image",
        ]

    class Meta:
        model = Post
        fields = ["title", "body", "image"]
        
        widgets = {
            "title": forms.TextInput(
                {
                    "class": "form-control bform",
                    "placeholder": "O titulo da sua publicação",
                }
            ),
            "body": forms.TextInput({"class": "form-control bform", "rows": 3}),
            "image": forms.FileInput(
                {"class": "form-control-file bform", "accept": "image/*"}
            ),
        }

        labels = {
            "title": "Título ",
            "body": "Texto da publicação :",
            "image": "Insira aqui a imagem dessa publicação",
        }

class CreateCommentForm(forms.ModelForm):
    class Meta :
        model = Comment           

        fields = ["body"]

        widgets = {"body": forms.TextInput({"class": "form-control comentbar", "rows": 6})}
        labels = {"body": "Digite aqui seu comentário"}

blog/views.py
from django.views.generic import DetailView, ListView, CreateView
from django.views import View
from django.shortcuts import redirect, get_object_or_404
from .models import Post, Comment, Category, Favorite

from .forms import CreatePostForm, CreateCommentForm
class PostListView(ListView):
    model = Post
    category = None
    paginate_by = 6

    def get_queryset(self):
        queryset = Post.objects.all()

        category_slug = self.kwargs.get("slug")
        if category_slug:
            self.category = get_object_or_404(Category, slug=category_slug)
            queryset = queryset.filter(category=self.category)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = self.category
        context["categories"] = Category.objects.all()
        return context
class PostDetailView(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["comment_form"] = CreateCommentForm()
        return context
    
    def post(self, request, **kwargs):
        form = CreateCommentForm(request.POST)  
        
        if form.is_valid():
            form.instance.post = self.get_object()
            form.instance.author=request.user
            form.save()
        return redirect(request.path)

class PostCreateView(CreateView):
    model = Post
    form_class = CreatePostForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
class CommentListView(ListView):
    model = Comment

class FavoriteView(View):

    def post(self,request):

        user = request.user
        post_id = request.POST.get("post_id")
        post_obj = Post.objects.get(id=post_id)
            
        if user in post_obj.favorite.all():
                post_obj.favorite.remove(user)
        else :
                post_obj.favorite.add(user)

        favorite, created = Favorite.objects.get_or_create(author = user, post_id=post_id)

        if not created:
            if favorite.value == "Favoritar":
                favorite.value = "Desfavoritar"
            else:
                favorite.value = "Favoritar"
        favorite.save()

        return redirect(post_obj.get_absolute_url())

templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<div class="post-detail">
    <div class="col-12">
    <div>
    <h2 class="ptitle">{{ post.title }}</h2>
    </div>
    <div class="post-img container">            
        {% if post.image %}
                    <img src="{{ post.image.url }}" class="post-img" alt="{{ post.title }}">                            
                    {% else %}
                    <img src="{% static 'images/no_image.jpg' %}" class="post-img" alt="Post">
                    {% endif %}
    </div>                           
    <p class="date">
        Publicado em {{ post.created }} por {{ post.author }}       
    </p>    
    {{ post.body|linebreaks }}
    <form action="{% url 'blog:favorite' %}" method="POST" >
        {% csrf_token %}
        <input type="hidden" name='post_id' value="{{ post.id }}">
        {% if user not in post.favorite.all %}
        
        <button class="btn btn-outline-danger" type="submit"> 
            <svg class="ico-heart" width="54" height="54" viewBox="0 0 24 24">
                <path d="M12,21.35L10.55,20.03C5.4,15.36 2,12.27 2,8.5C2,5.41 4.42,3 7.5,3C9.24,3 10.91,3.81 12,5.08C13.09,3.81 14.76,3 16.5,3C19.58,3 22,5.41 22,8.5C22,12.27 18.6,15.36 13.45,20.03L12,21.35Z"></path>
            </svg></button> 
        {% else %}
            <button class="btn btn-outline-danger" type="submit"> 
                <svg class="ico-heart liked" width="54" height="54" viewBox="0 0 24 24">
                    <path d="M12,21.35L10.55,20.03C5.4,15.36 2,12.27 2,8.5C2,5.41 4.42,3 7.5,3C9.24,3 10.91,3.81 12,5.08C13.09,3.81 14.76,3 16.5,3C19.58,3 22,5.41 22,8.5C22,12.27 18.6,15.36 13.45,20.03L12,21.35Z"></path>
                </svg></button>
        {% endif %}
    </form> 
    <p>{{ post.favorite.all.count }} Favoritos</p>
    <div class="btn-group espaco">

        <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Comente
        </button>
        <div class="dropdown-menu drop">   
          <a class="dropdown-item" >
              {% if user.is_authenticated %}     
            <form  method="POST">
                {{ comment_form }} 
                {% csrf_token %}
                <button value="submit" class="btn btn-success">Enviar</button>
            </form>
            {% else %}
            <p class="warning">Você precisa estar logado para comentar aqui</p>
            {% endif %}
        </a>  
        </div>
      </div>   
    
</div>
</div>


<!--Comentarios-->
{% if post.comment_set.all %}

<div id = "comments" class="container">
	<div class="row">
        <h2 class="ctitle"> {{ post.comment_number }} Comentários:</h2>
		<div class="MultiCarousel" data-items="1,3" data-slide="1"
         id="MultiCarousel"  data-interval="10">
            <div class="MultiCarousel-inner">                
        {% for comment in post.comment_set.all %}
                <div class="item" >
                    <div class="pad15">
                        <p class="lead">{{ comment.author }} comentou : </p>
                        <p class="comlead"> " {{ comment.body }} "</p>
                        <p class="lead">Comentário feito em {{ comment.created }}</p>                        
                    </div>
                </div>                
    {% endfor %} 
            </div>
            <button class="btn btn-primary leftLst"><</button>
            <button class="btn btn-primary rightLst"">></button>
        </div>
	</div>
</div>
{% endif %}


{% block script %}
<script src="{% static 'js/boot-slider.js' %}"></script>
{% endblock script %}
{% endblock %}

templates/blog/post_form.html
{% extends "base.html" %}

{% block title %} Criar meu post {% endblock title %}

{% block content %}
<div class="container">  
<form class="bcreate" method="POST">
  <div class="">
    <h2 class="actitle">Criar sua publicação</h2>
    {{ form }}
    {% csrf_token %}
    
  <button type="submit" class="btn btn-success">Criar</button>
  </div>
</form>
</div>
{% endblock %}

templates/blog/post_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}Blog{% endblock %}
{% block content %}

<div>    
    <div class="loader-wrapper" style="z-index:200001">
      <span class="loader"><span class="loader-inner"></span></span>
    </div>
<div class="btn-group">
    <button type="button" class="gradient-button gradient-button-1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        
     Categorias
    </button>
    <ul class="dropdown-menu dropdown-menu-dark">   
      <li><a class="dropdown-item" href="{% url 'blog:list' %}">Todos as publicações </a></li>
      
      {% for cat in categories %}
      <li><a class="dropdown-item" href="{{ cat.get_absolute_url }}">
          {{ cat.name }}
      </a></li>
      
      {% endfor %}
    </ul>
</div>

    {% for post in post_list %}
<div class="col-9">
    <div class="post">
        <article class= "">
            <div class="titlep">
            <h2 class = "titlep">
                <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}  
                </a>
            </h2>
            </div>
            <a href="{{ post.get_absolute_url }}">   
            <div class="container">            
            {% if post.image %}
                <img src="{{ post.image.url }}" class="post-img" alt="{{ post.title }}">                            
                {% else %}
                <img src="{% static 'images/no_image.jpg' %}" class="post-img" alt="{{ post.title }}">
                {% endif %}
            </div>
        </a><p class="date">
            Publicado em {{ post.created }} por {{ post.author }}
            </p><img class="rounded-circle" src='{{ post.author.profile.image.url }}'>                     
            {{ post.body|linebreaks|truncatewords:15 }}
            <div class="post-fav">         
                
                <button type="button" class="btn btn-outline-primary btn-floating btn-com">
                    <i class="fas fa-comment letter"></i>
                </button>   
                
                <form action="{% url 'blog:favorite' %}" method="POST" >
                    {% csrf_token %}
                    <input type="hidden" name='post_id' value="{{ post.id }}">
                    {% if user not in post.favorite.all %}
                    
                    <button class="btn btn-outline-danger" type="submit"> 
                        <svg class="ico-heart liked" width="54" height="54" viewBox="0 0 24 24">
                            <path d="M12,21.35L10.55,20.03C5.4,15.36 2,12.27 2,8.5C2,5.41 4.42,3 7.5,3C9.24,3 10.91,3.81 12,5.08C13.09,3.81 14.76,3 16.5,3C19.58,3 22,5.41 22,8.5C22,12.27 18.6,15.36 13.45,20.03L12,21.35Z"></path>
                        </svg></button> 
                    {% else %}
                        <button class="btn btn-outline-danger" type="submit"> 
                            <svg class="ico-heart" width="34" height="34" viewBox="0 0 24 24">
                                <path d="M12,21.35L10.55,20.03C5.4,15.36 2,12.27 2,8.5C2,5.41 4.42,3 7.5,3C9.24,3 10.91,3.81 12,5.08C13.09,3.81 14.76,3 16.5,3C19.58,3 22,5.41 22,8.5C22,12.27 18.6,15.36 13.45,20.03L12,21.35Z"></path>
                            </svg></button>
                    {% endif %}
                </form>   
                <p>{{ post.favorite.all.count }} Favoritos</p>
                <p> {{ post.comment_number }} Comentários</p> 
            </div>            
        </article>
    </div>
</div>
    {% endfor %}
    <div id="voltarTopo">
        <a class="midle" href="" id="subir">▲</a>
    </div>
</div>




{% if is_paginated %}
            {% include "pagination.html" with page=page_obj %}
    {% endif %}
{% endblock %}