blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.PostListView.as_view(), name="list"),
    path("criar/", views.PostCreateView.as_view(), name="create"),
    path("category/<slug:slug>/", views.PostListView.as_view(), name="list_by_category"),
    path("post/<slug:slug>/", views.PostDetailView.as_view(), name="detail"),
    path("favorito/", views.FavoriteView.as_view(), name="favorite"),    
]

cart/urls.py
from django.urls import path
from .views import cart_detail, cart_add, cart_remove

app_name = "cart"

urlpatterns= [
    path("", cart_detail, name="detail"),
    path("add/<int:product_id>/", cart_add, name= "add"),
    path("remove/<int:product_id>/", cart_remove, name= "remove"),
]

pages/urls.py
from django.urls import path

from .views import AboutPageView, HomePageView

app_name = "pages"

urlpatterns = [
    path("sobre/", AboutPageView.as_view(), name="about"),
    path("", HomePageView.as_view(), name="home"),
    
]

products/urls.py
from django.urls import path

from .views import ProductDetailView, ProductListView

app_name = "products"

urlpatterns = [
    path("", ProductListView.as_view(), name="list"),
    path("<slug:slug>/", ProductDetailView.as_view(), name="detail"),
    path("category/<slug:slug>/", ProductListView.as_view(), name="list_by_category"),
]

pycom/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("produtos/", include("products.urls")),
    path("carrinho/", include("cart.urls")),
    path("", include("pages.urls")),
    path("orders/",include("orders.urls")),    
    path("accounts/",include("allauth.urls")),
    path("payments/", include("payments.urls")),
    path("blog/", include("blog.urls")),
    path("perfil/", include("users.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

users/urls.py
from django.urls import path

from users import views as user_views

app_name = "users"

urlpatterns = [
    path("", user_views.profile, name="profile" ),
]

templates/about.html
{% extends 'base.html' %}

{% load static %}
{% block title %}Sobre Nós{% endblock title %}

{% block content %}

<div class="container my-3">
    <h1 align="center" class="font-weight-bold">Sobre nós</h1>    
    <div class="ab-img">
        <ul style="list-style-type: none;">
            <li><img src="{% static 'images/about/book.png' %}"><h2 class="ab-det">Conhecimento</h2>
                <p class="ab-det">Criamos a época da velocidade, mas nos sentimos enclausurados
                     dentro dela. A máquina, que produz abundância, tem-nos deixado em penúria.</p>
    </li>
            <li>
    <img src="{% static 'images/about/brain.png' %}"><h2 class="ab-det"> Intelectualidade</h2>
    <p class="ab-det">Criamos a época da velocidade, mas nos sentimos enclausurados
        dentro dela. A máquina, que produz abundância, tem-nos deixado em penúria.</p>
            </li>
        </ul>
    </div>
    <div class="ab-img">
        <ul style="list-style-type: none;"><li><img src="{% static 'images/about/balanca.png' %}"><h2 class="ab-det">Igualdade</h2>
            <p class="ab-det">Criamos a época da velocidade, mas nos sentimos enclausurados
                dentro dela. A máquina, que produz abundância, tem-nos deixado em penúria.</p>
            </li>
            <li><img src="{% static 'images/about/lamp.png' %}"><h2 class="ab-det"> Liberdade</h2>
                <p class="ab-det">Criamos a época da velocidade, mas nos sentimos enclausurados
                    dentro dela. A máquina, que produz abundância, tem-nos deixado em penúria.</p>
            </li>
        </ul>
    </div>    
</div>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="pt-BR">

{% load static %}
{% load product_tags %}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- css style sheets -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">        
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css"> 
    <link rel="stylesheet" href="{% static 'css/slick.css' %}" type="text/css"> 
    <title>{% block title %}Loja Python{% endblock title %}</title>
</head>

<body class="d-flex flex-column min-vh-100">    
    <nav class="navbar navbar-expand-lg navbar-dark top-navg">  
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" 
        aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>          
          <a class="navbar-brand" href="{% url 'pages:home' %}"><h4>Piratas</h4></a>        
      <!-- Esquerda navegador-->
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item "><a class="nav-link" href="{% url 'pages:home' %}"><p class="navtile nav-c">Principal</p></a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'products:list' %}"><p class="navtile nav-c">Produtos</p></a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'pages:about' %}"><p class="navtile nav-c">Sobre nós</p></a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'blog:list' %}"><p class="navtile nav-c">Blog</p></a></li>
          </ul>
      <!-- Direita navegador-->
          <ul class="navbar-nav ml-auto">            
            {% if user.is_authenticated %}                
            <li class="nav-item nav-link espaco"><a href="{% url 'users:profile' %}"> <p class="navtile">Olá {{ user.username }} !</p></a></li>         
            
            <div class="btn-group espaco">
              <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Posts
              </button>
              <div class="dropdown-menu drop">   
                <a class="dropdown-item" href="{% url 'blog:create' %}">Criar Publicação</a>             
                <a class="dropdown-item" href=""><i class="fas fa-heart"></i> Favoritos</a>                
                <a class="dropdown-item" href="#">Destaques</a>
              </div>
            </div>
            <div class="btn-group espaco">
              <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Loja
              </button>
              <div class="dropdown-menu drop" >                
                <a class="dropdown-item" href="{% url 'cart:detail' %}"><i class="fas fa-dolly-flatbed"></i> 
                  Carrinho 
                    {% with total_itens=cart|length %}
                    {% if total_itens > 0 %}
                    ({{ total_itens }})
                    {% else %}
                    (0)
                    {% endif %}
                    {% endwith %}                  
                </a>
                <a class="dropdown-item" href=""><i class="fas fa-heart"></i> Favoritos</a>
                <a class="dropdown-item" href="#">Promoções</a>
              </div>
            </div>
            <li class="nav-item"><a class="nav-link espaco" href="{% url 'account_logout' %}"><p class="navtile"><i class="fas fa-sign-out-alt"></i> Logout</p></a></li>
            <div>
              <input type="checkbox" onClick="save()" class="checkbox" id="chk" />
              <label class="label" for="chk">
                <p class="navtile"><i class="fas fa-moon"></i></p>
                <p class="navtile"><i class="fas fa-sun"></i></p>                
                <div class="ball"></div>
              </label>
            </div>
            {% else %}            
            <li class="nav-item"><a class="nav-link" href="{% url 'account_login' %}"> <i class="fas fa-user-alt mr-1 text-gray"></i> Login</a></li>
            <li class="nav-item"><a class="nav-link espaco" href="{% url 'account_signup' %}"><i class="fas fa-user-edit"></i> Cadastro</a></li>
            <div>
              <input type="checkbox" class="checkbox" id="chk" />
              <label class="label" for="chk">
                <i class="fas fa-moon"></i>
                <i class="fas fa-sun"></i>
                <div class="ball"></div>
              </label>
            </div>
            {% endif %}
          </ul>
          <!-- Aqui esta a barra de pesquisa futura
            <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Procurar" aria-label="Procurar">
            <button class="btn btn-primary my-2 my-sm-0" type="submit">Pesquisar</button>
          </form>-->
        </div>

      </nav>
      

    {% block content %}
    {% endblock content %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
        integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"
     integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
      crossorigin="anonymous">
    <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>      
    <script src="{% static 'js/darktheme.js' %}"></script>    
    <script src="{% static 'js/slick.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    {% comment %} <script src="{% static 'js/index.js' %}"></script> {% endcomment %}

    {% block script %}
    {% endblock script %}

</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Os Unipar Piratas{% endblock %}
{% block content %}
{% comment %} <link type="text/css" href="{% static 'css/chuva.css' %}" rel="stylesheet"> {% endcomment %}
<body onload="carregar()"> 
  {% comment %} <div onload="carregar()" {% endcomment %}
  
  {% comment %} </div> {% endcomment %}
  {% comment %} <script src="{% static 'matrix_effect.js' %}"></script> {% endcomment %}

  <div class="rain"></div>
  <div class="background-image"></div>
  <div class="loader-wrapper" style="z-index:200001">
    <span class="loader"><span class="loader-inner"></span></span>
  </div>
  <!-- Banner -->
  <div class="d-block w-100">
  <section>   
    <img class='dia' src="{% static 'images/hero/dia.png' %}" id="dia">     
    <img class="sol" src="{% static 'images/hero/sol.png' %}" id="sol">  
    <img class= "lua" style="z-index: 2" src="{% static 'images/hero/lua.png' %}" id="lua">        
    <h2  class="hubtitle" font-style="" id="hub">Os Unipar Piratas --HEAD</h2>
    <img style="z-index: 2; width: 80%;" src="{% static 'images/hero/git.png' %}" id="git">
    <img style="z-index:5" src="{% static 'images/hero/montanhas.png' %}" id="montanhas"> 
    <img class="mont" style="z-index:5" src="{% static 'images/hero/montanhas-dia.png' %}" id="montanhas-d">  
    <img style="z-index:200000" src="{% static 'images/hero/forest.png' %}" id="forest">  
  </section>
  <script type="text/javascript">
  let sol = document.getElementById("sol")  
  let lua = document.getElementById("lua")
  let Piratas = document.getElementById("hub")
  let montanhas = document.getElementById("montanhas")
  let montanhasd = document.getElementById("montanhas-d")
  let forest = document.getElementById("forest")
  let git = document.getElementById("git")  

  window.addEventListener('scroll', function(){
    var value = window.scrollY;
    Piratas.style.top = value * 0.4 + 'px';    
    montanhas.style.top = value * -(0.8) + 'px'; 
    montanhasd.style.top = value * -(0.8) + 'px';    
    lua.style.left = value * -0.6 + 'px';
    sol.style.left = value * -0.6 + 'px';
    forest.style.top = value * -(0.45) + 'px';     
    git.style.top = value * 0.6 + 'px'; 
    disc.style.top = value * 0.05 + 'px'; 
  })

  </script>


  {% comment %} <div class="container tdisc">
  <a href="https://discord.gg/Xg6FcXGp7x">
    <h2 class="text-disc"> Venha conhecer nosso servidor</h2>
    <img class="card-disc" src="{% static 'images/discord-logo.png' %}" alt="Discord">
  </a>
  </div> {% endcomment %}

  <!-- seção carrocel -->

  <div class="for_slick_slider multiple-items">
  <div class="items"><img src="{% static 'images/banner/banner-1.jpg' %}" alt="" /></div>
  <div class="items"><img src="{% static 'images/banner/banner-2.jpg' %}" alt="" /></div>
  <div class="items"><img src="{% static 'images/banner/banner-3.jpg' %}" alt=""/></div>
  <div class="items"><img src="{% static 'images/banner/banner-4.jpg' %}" alt="" /></div>
  <div class="items"><img src="{% static 'images/banner/banner-5.jpg' %}" alt="" /></div>
  <div class="items"><img src="{% static 'images/banner/banner-6.jpg' %}" alt="" /></div>
  </div>

  <!-- seção produtos teste -->
  <div class="ptop">
  <div class="text-center">
  <p class="text-uppercase mb-1">Saiba sobre o que estão falando hoje :</p>
  <h1 class="h5 text-uppercase mb-4">Principais publicações !</h2>
  </div>
  <div class="d-flex w-100">
  <div class="row">
  <div class="col-sm">
  <div class="card op cards">       
  <img class="card-img-top" src="{% static 'images/hero.jpg' %}" alt="Imagem de capa do card">
  <div class="card-body ">
    <h5 class="card-title">Post 1</h5>
    <p class="card-text card-dt">Um exemplo de texto rápido para construir o título do card e fazer preencher o conteúdo do card.</p>
  </div>  
  <div class="btn-group" role="group" aria-label="Basic example">
    <button type="button" class="btn btn-primary">Link do card</button>
    <button type="button" class="btn btn-secondary">Outro link</button>
  </div>
  </div>
    </div>
    <div class="col-sm">
      <div class="card op cards">
        <img class="card-img-top" src="{% static 'images/hero.jpg' %}" alt="Imagem de capa do card">
        <div class="card-body">
          <h5 class="card-title">Post 2</h5>
          <p class="card-text card-dt">Um exemplo de texto rápido para construir o título do card e fazer preencher o conteúdo do card.</p>
        </div>
        <div class="btn-group" role="group" aria-label="Basic example">
          <button type="button" class="btn btn-primary">Link do card</button>
          <button type="button" class="btn btn-secondary">Outro link</button>
        </div>
      </div>
    </div>
    <div class="col-sm ">
      <div class="card op cards" >
        <img class="card-img-top" src="{% static 'images/hero.jpg' %}" alt="Imagem de capa do card">
        <div class="card-body">
          <h5 class="card-title">Post 3</h5>
          <p class="card-text card-dt">Um exemplo de texto rápido para construir o título do card e fazer preencher o conteúdo do card.</p>
        </div>
        <div class="btn-group" role="group" aria-label="Basic example">
          <button type="button" class="btn btn-primary">Link do card</button>
          <button type="button" class="btn btn-secondary">Outro link</button>
        </div>
      </div>
    </div>
  </div>
  </div>
  </div>

{% comment %} <div class="canvas-background">
  <canvas id="canvas1"></canvas>
</div> {% endcomment %}

  <div class="container my-3">
    <h1 align="center" class="font-weight-bold">Sobre os Unipar Piratas</h1>
    <p>Os Unipar Piratas representam uma comunidade acadêmica diversa e apaixonada pela tecnologia. Este grupo multifacetado é composto por entusiastas do conhecimento, incluindo hackers éticos, programadores talentosos, analistas perspicazes e designers de experiência do usuário (UX) criativos.</p>

    <p>Exploramos desde os fundamentos mais básicos até os conceitos avançados nas áreas de tecnologia e informática. Nosso objetivo é promover a aprendizagem colaborativa e o compartilhamento de conhecimento para impulsionar a inovação e o progresso.</p>
    
    <p>Juntos, navegamos pelos mares da informação, desvendando os segredos da programação, da segurança cibernética e da análise de dados. Somos apaixonados por desafios e estamos comprometidos em expandir nossos horizontes tecnológicos.</p>
    
    <p>Se você é um entusiasta da tecnologia em busca de um grupo dedicado e acolhedor para aprender e crescer, junte-se a nós e embarque nessa jornada emocionante com os Unipar Piratas!</p>
    
  </div>
  </body> 
  <div id="voltarTopo">
  <a class="midle" href="#" id="subir">▲</a>
  </div>

  <footer class="bg-dark text-white">
    <div class="container py-4">
      <div class="row py-5">
        <div class="col-md-4 mb-3 mb-md-0">
          <h6 class="text-uppercase mb-3 h5">Serviços de consumidores</h6>
          <ul class="list-unstyled mb-0">
            <li><a class="text-decoration-none footer-link li h6" href="#">Ajuda &amp; Nos contate</a></li>
            <li><a class="text-decoration-none footer-link li h6" href="#">Loja online</a></li>
            <li><a class="text-decoration-none footer-link li h6" href="#">Temos &amp; Condições</a></li>
          </ul>
        </div>
        <div class="col-md-4 mb-3 mb-md-0">
          <h6 class="text-uppercase mb-3 h5">Companhia</h6>
          <ul class="list-unstyled mb-0">
            <li><a class="text-decoration-none footer-link li h6" href="#">O que nós fazemos</a></li>
            <li><a class="text-decoration-none footer-link li h6" href="#">Últimas Publicações</a></li>
            <li><a class="text-decoration-none footer-link li h6" href="#">Fale conosco</a></li>
          </ul>
        </div>
        <div class="col-md-4">
          <h6 class="text-uppercase mb-3 h5">Midias sociais</h6>
          <ul class="list-unstyled mb-0">
            <li><a class="text-decoration-none footer-link li h6" href="">Discord <i class="fab fa-discord" style="font-size: 1.5em"></i></a></li>
            <li><a class="text-decoration-none footer-link li h6" href="">Twitter <i class="fab fa-twitter" style="font-size: 1.5em"></i></a></li>
            <li><a class="text-decoration-none footer-link li h6" href="">Instagram <i class="fab fa-instagram" style="font-size: 1.5em"></i></a></li>
            <li><a class="text-decoration-none footer-link li h6" href="">Github  <i class="fab fa-github" style="font-size: 1.5em"></i></a></li> 
          </ul>
        </div>
      </div>
      <div class="border-top pt-4" style="border-color: #1d1d1d !important">
        <div class="row">
          <div class="col-lg-6">
            <p class="small text-muted mb-0">&copy; 2121 Todos os direitos reservados.</p>
          </div>
          <div class="col-lg-6 text-lg-right">
            <p class="small text-muted mb-0">Template criado em <a href="https://getbootstrap.com/">bootstrap</a> por <a class="text-white reset-anchor" href="">Jackson Zacarias</a></p>
          </div>
        </div>
      </div>
    </div>
    {% comment %} <script type="text/javascript" src="/static/js/main.js"></script> {% endcomment %}
  </footer>
  {% endblock content %}

templates/order_summary.html
<div class="card border-0 bg-light p-4">
    <h4>Resumo do Pedido</h4>
    <ul class="list-group list-group-flush">
        {% for item in items %}
        <li class="list-group-item bg-light">
            {{ item.quantity }}x {{ item.product.name }}
            <span class="float-right">R$ {{ item.total_price }}{{ item.get_total_price }}</span>
        </li>
        {% endfor %}
        <li class="font-weight-bold list-group-item bg-light">Total
            <span class="float-right">R$ {{ total_price }}</span>
        </li>
    </ul>
</div>

templates/pagination.html
<div aria-label="Page navigation example">

    <ul class="pagination justify-content-center ">
        {% if page.has_previous %}
        <li class="page-item pagnt">
            <a class="page-link" href="?page={{ page.previous_page_number }}" tabindex="-1">
              <i class="fas fa-angle-double-left"></i></a>
          </li>
          {% endif %}          
          {{ page.page_range }}
          {% for i in page.paginator.page_range %}
          <li class="page-item"><a class="page-link" href="?page={{i}}" data-page={{i}}>{{i}}</a></li>
          {% endfor %}
          {% if page.has_next %} 
          <li class="page-item">
            <a class="page-link" href="?page={{ page.next_page_number }}">
              <i class="fas fa-angle-double-right"></i></a>
          </li>
          {% endif %}
        </ul>
      </div>

      